### ISSUE TITLE
String compared to an integer

### ISSUE THREAD

**Issue by tombaker** [tombaker/mklists#1]
```
Traceback (most recent call last):
  File "/Users/tbaker/github/tombaker/shawkle/shuffle.py", line 518, in <module>
    rules                  = getrules(arguments.globalrules, arguments.localrules)
  File "/Users/tbaker/github/tombaker/shawkle/shuffle.py", line 201, in getrules
    if linesplitonorbar[4] < 1:
TypeError: unorderable types: str() < int()

**Comment by tombaker** [comment]
This is no longer relevant...
